name: Deploy Expo App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only on the main branch. You can change this to your default branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the version of Node.js compatible with Expo

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm install -g expo-cli
        npm install

    # Step 4: Build the Expo app
    - name: Build Expo App
      run: expo build:web

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web-build  # The directory where Expo outputs the build for web
        publish_branch: gh-pages   # The branch for the GitHub Pages site (make sure this branch exists)
