name: Deploy Expo App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only on the main branch. Adjust if necessary.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to use the latest version of the action

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Use Node.js version 22

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm install -g expo-cli  # Install Expo CLI globally
        npm install --save-dev gh-pages  # Install gh-pages for deployment
        npm ci  # Install dependencies using the package-lock.json for consistent builds

    # Step 4: Build the Expo app for web
    - name: Build Expo App
      run: |
        npx expo export --platform web --clear  # Corrected Expo command to build the web app

    # Step 5: Configure baseUrl for GitHub Pages (you can customize it based on your repo name)
    - name: Set baseUrl in app.json
      run: |
        sed -i 's/"baseUrl": ""/"baseUrl": "\/expo-gh-pages"/' app.json  # Modify baseUrl for deployment

    # Step 6: Set Git configuration for deploying
    - name: Set Git configuration
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}".insteadOf "https://github.com"  # Use GitHub token for authentication

    # Step 7: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      run: |
        npm run deploy  # This will run the gh-pages deployment script from package.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
